steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "gcloud"
    args:
      [
        "storage",
        "rsync",
        "--delete-unmatched-destination-objects",
        "--recursive",
        "./markdown",
        "gs://teachable-machine-snippets/github",
      ]
    dir: "snippets"

  - name: "gcr.io/cloud-builders/gsutil"
    entrypoint: "zip"
    args: ["-r", "TMConnector.zip", "TMConnector/"]
    dir: "snippets/markdown/tiny_image/tiny_templates"

  - name: "gcr.io/cloud-builders/gsutil"
    entrypoint: "zip"
    args: ["-r", "TMUploader.zip", "TMUploader/"]
    dir: "snippets/markdown/tiny_image/tiny_templates"

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "gcloud"
    args: ["storage", "cp", "*.zip", "gs://tiny-templates"]
    dir: "snippets/markdown/tiny_image/tiny_templates"
